// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywosoqjzagmwhkybelqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3b3NvcWp6YWdtd2hreWJlbHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDk4NTMsImV4cCI6MjA3MDE4NTg1M30.oqHQaS3ETKzwrLtycOJ3UXFgX5Katx-wduwIOKC0KBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});